project:
  type: website
  output-dir: docs

website:
  title: "ABI-ITWG"
  description: "A base for training content from the ABI Interim Training Working Group"
  favicon: ""

  navbar:
    logo: "✦"
    title: "ABI-ITWG"
    left:
      - text: "Home"
        href: index.qmd
      - text: "Training Materials"
        href: projects.qmd
      - text: "About"
        href: about.qmd

  page-footer:
    left: "© 2026 ABI-ITWG. CC BY"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    toc-title: "On this page"
    smooth-scroll: true
    code-copy: true
    code-overflow: wrap
    highlight-style: github
