---
title: "ABI Summer School 2026"
description: "Materials for the Summer School 08 - 19 June 2026"
toc: true
---

## About the event:
The aim is to provide comprehensive training on bioinformatics computational resources, and domain-specific tools and workflows to improve participants' proficiency in executing, interpreting, and communicating analyses for major bioinformatics studies, with a special focus on genomics.

---

## Course Content:

### Week 1: 

#### Linux and High Performance Computing
1. [Introduction to Linux & HPC](week1/unix-and-HPC/intro_to_linux.qmd)
2. [Linux Basics Recap](week1/unix-and-HPC/Linux_Basics_Recap.md)
3. [Bash Scripting I & HPC Job Submission](week1/unix-and-HPC/Bash_scripting_I_and_HPC_Job_Submission.md)
4. [File processing with sed](week1/unix-and-HPC/file-processing-sed.md)
5. [File processing with awk](week1/unix-and-HPC/file-processing-awk.md)
6. [Bash Scripting II](week1/unix-and-HPC/Bash_scripting_II.md)
7. [Containers](week1/unix-and-HPC/Containers.md)
8. [Day One Assignment](week1/unix-and-HPC/Day_1_Assignment.md)

#### R programming


#### Intro to NGS


---

### Week 2 

#### Human Genomics
1. [Introduction to Human Genomics: Overview of Data QC and Analysis Workflow]
2. [Practical: Read alignment using BWA-MEM and QC]
3. [Principles of Human Variant Calling]
4. [Variant Calling Practical using GATK HaplotypeCaller] (week2/human-genomics/short-read-snv-analysis/variant-calling-brca1-tutorial.md)
5. [Variant Filtering and Exploration — Single-sample and Multi-sample VCF Files]
6. [Introduction to Workflow Automation using Nextflow]
7. [Practical: Human Variant Calling Workflow Automation using Nextflow]
8. [Principles of Variant Annotation and Variant Effect Prediction]
9. [Practical: Variant Annotation/Prioritisation]
10. [Statistical Phasing Concepts and Practical Example using 1000 Genomes Project data]
11. [Overview of long-read sequencing technologies and data analysis tools]
12. [Practical: Oxford Nanopore read alignment and variant calling](week2/human-genomics/long-read-snv-analysis/ont/ont-analysis-practical-1.md)
13. [Introduction to Structural Variation Analysis]
14. [Practical: Structural variant calling and annotation]
15. [Course assessment]


#### Pathogen Genomics
1. [Basics of Bacterial Genomes](week2/pathogen_genomics/Day_1/basics.qmd)
2. [Quality Control of Sequencing Data](week2/pathogen_genomics/Day_1/qc.qmd)
3. [Assembly Principles: Reference Vs De Novo](week2/pathogen_genomics/Day_2/assembly_principles.qmd)
4. [Genome Alignment & Variant Calling](week2/pathogen_genomics/Day_2/genome.qmd)
5. [Bacterial Genome Annotation](week2/pathogen_genomics/Day_3/annotation.qmd)
6. [Pan-genome Analysis & Multilocus Sequence Typing](week2/pathogen_genomics/Day_3/pangenome.qmd)
7. [Mechanisms of AMR & Virulence](week2/pathogen_genomics/Day_4/mechanisms.qmd)
8. [Horizontal Gene Transfer & Mobile Genetic Elements](week2/pathogen_genomics/Day_4/mge.qmd)
9. [Applications of Bacterial Genomics: AMR Surveillance](week2/pathogen_genomics/Day_5/applications.qmd)

#### Metagenomics
1. [Quality Control](week2/metagenomics/qc.md)
2. [Amplicon Data Analysis](week2/metagenomics/qiime2-amplicon.md)
3. [Diversity Analysis](week2/metagenomics/diversity-analysis.md)
4. [Shotgun Metagenomics](week2/metagenomics/shortgun-metagenomics.md)
5. [Metagenome-Assembled Genomes](week2/metagenomics/metagenome-assembled-genomes.md)
6. [Functional Analysis](week2/metagenomics/functional-analysis.md)
7. [Visualisation & Mini-Project](week2/metagenomics/functional-analysis-visualisation.md)

---

## Trainer Info

| Name | Affiliation | Role | Stream |
|------|-------------|------|--------|
| Gloria Nakabiri | African Center of Excellence in Bioinformatics and Data Intensive Sciences | Lead trainer | Unix |
| Peter van Heusden | South African National Bioinformatics Institute (SANBI) | Lead trainer | R |
| Ian Wasukira | African Center of Excellence in Bioinformatics and Data-Intensive Sciences | Lead Trainer | Unix/HPC |
| Ronald Galiwango | African Center of Excellence in Bioinformatics and Data-Intensive Sciences | Lead trainer | R |
| Musalula Sinkala | University of Cape Town | Lead trainer | Human Genomics |
| Dayna Adrienne Croock | Stellenbosch University | Lead trainer | Human Genomics |
| John Juma | International Livestock Research Institute (ILRI) | Lead trainer | Pathogen Genomics |
| Damien Tully | MRC/UVRI & LSHTM Uganda Research Unit | Lead Trainer | Pathogen Genomics |
| Alfred Ssekagiri | Uganda Virus Research Institute | Lead trainer | Metagenomics |
| Yohannes Gedamu Gebre | Bio and Emerging Technology Institute (BETin); former Ethiopia Biotechnology Institute (EBTi) | Co-trainer | Unix/R/Pathogen Genomics |
| Keaghan Brown | PHA4GE | Co-trainer | Pathogen Genomics |
| Amadou Diallo | Pioneer Bio-Analytics | Co-trainer | Metagenomics |
| Ephifania Geza | University of Cape Town | Lead trainer | Metagenomics |
| Patricia Nabisubi | The African Centre of Excellence in Bioinformatics and Data Intensive Sciences | Co-trainer | Unix/R/NGS basics |
| Trushar Shah | International Livestock Research Institute (Kenya) | Co-trainer | Human Genomics/Unix |
| Daria Sokolova | European Bioinformatics Institute (EBI) | Core organiser/support | |
| Grace Kebirungi | African Center of Excellence in Bioinformatics and Data-Intensive Sciences | Core organiser/support | |
| David Twesigomwe | MRC/UVRI & LSHTM Uganda Research Unit | Core organiser/support | |
| Verena Ras | African Bioinformatics Institute / University of Cape Town | Core organiser/support | |
| Shaun Aron | Sydney Brenner Institute for Molecular Bioscience (SBIMB) / University of Witwatersrand | Core organiser/support | |
| Melek Chaouch | Institut Pasteur, Tunis | Core organiser/support | |
| Jorge da Rocha | European Bioinformatics Institute (EBI) | Core organiser/support | |



